# load variables from .env file in the root if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

lane :test do
  upload_to_app47(
    account_token: ENV["TEST_APP47_ACCOUNT_TOKEN"],
    app_id: ENV["TEST_APP47_APP_ID"],
    ipa_path: './fastlane/app-release.ipa', # optional defaults to IPA_OUTPUT_PATH
    environment: 'Test',
    make_active: true,
    reset_bundle_identifier: true,
    reuse_version: true,
  )
end
